default:
  just --list

run FILE:
  -LD_LIBRARY_PATH=. ./nbacg.opt {{FILE}} -analysis 2 +valid -postpre "-drelation 1" -print "+p +a +r" -dot "{{FILE}}.dot +all"
  dot -Tpng -O {{FILE}}.dot

options:
  -LD_LIBRARY_PATH=. ./nbacg.opt

